/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a2.f1_fantasy;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author ALUMNOS
 */
public class Inicio extends javax.swing.JFrame {
    
    /**
     * Creates new form Frame_f1
     */
    public Inicio() {
     setTitle("Fantasy");
     setSize(500, 600);
     setDefaultCloseOperation(Inicio.EXIT_ON_CLOSE);
     setLocationRelativeTo(null);
     setLayout(new GridBagLayout());
     GridBagConstraints gbcPrincipal = new GridBagConstraints();
     gbcPrincipal.fill = GridBagConstraints.BOTH;
     JPanel panelSuperior = crearPanelSuperior();
     gbcPrincipal.gridx = 0; 
     gbcPrincipal.gridy = 0; 
     gbcPrincipal.weightx = 0.6; 
     gbcPrincipal.weighty = 0.5; 
     gbcPrincipal.insets = new Insets(10, 10, 5, 5); 
     add(panelSuperior, gbcPrincipal);
     

    }
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> {
        new Inicio().setVisible(true);
    });
}
private JPanel crearPanelSuperior() {
    JPanel panel = new JPanel();
    panel.setBorder(BorderFactory.createTitledBorder("FANTASY"));
    java.net.URL urlFondo = getClass().getResource("/imagenes/Fondo.jpg");
    Image imagen = new ImageIcon(urlFondo).getImage().getScaledInstance(500, 700, Image.SCALE_SMOOTH);

    JLabel fondo = new JLabel(new ImageIcon(imagen));
    fondo.setLayout(new GridBagLayout());
    GridBagConstraints c = new GridBagConstraints();

    // Logo encima del botón
    java.net.URL urlLogo = getClass().getResource("/imagenes/Logo.png");
    Image logo = new ImageIcon(urlLogo).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    c.gridx = 0;
    c.gridy = 0;
    c.insets = new Insets(0, 0, 20, 0);
    fondo.add(new JLabel(new ImageIcon(logo)), c);

    // Botón debajo
    
    JButton btnIniciar = new JButton("Iniciar");
    btnIniciar.addActionListener(e -> {
       
    });
    c.gridy = 1;
    c.insets = new Insets(0, 0, 0, 0);
    fondo.add(btnIniciar, c);
    btnIniciar.addActionListener(e -> {
            new Principal().setVisible(true); 
            dispose();                   
        });
    c.gridy = 1;
    c.insets = new Insets(0, 0, 200, 0); 
    fondo.add(btnIniciar, c);
    panel.add(fondo, BorderLayout.CENTER);
    
    return panel;
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
